# SwiftLint Configuration for LinkForty iOS SDK

# Disabled rules
disabled_rules:
  - trailing_whitespace

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - sorted_imports
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - non_optional_string_data_conversion

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 400
  error: 600

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - to
    - at
    - i

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Pods
  - Carthage
  - DerivedData
  - Examples

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    match_kinds:
      - identifier
    message: "Use LinkFortyLogger.log() instead of print()"
    severity: warning
