//
//  InstallResponse.swift
//  LinkFortySDK
//
//  Copyright (c) 2025 LinkForty
//  Licensed under the MIT License
//

import Foundation

/// Response from the install attribution API
public struct InstallResponse: Codable {
    /// Unique install ID generated by the backend
    public let installId: String

    /// Whether this install was attributed to a link click
    public let attributed: Bool

    /// Confidence score for attribution (0-100)
    public let confidenceScore: Double

    /// Which fingerprint factors matched
    public let matchedFactors: [String]

    /// Deep link data if attributed, nil if organic
    public let deepLinkData: DeepLinkData?

    // MARK: - Codable

    enum CodingKeys: String, CodingKey {
        case installId
        case attributed
        case confidenceScore
        case matchedFactors
        case deepLinkData
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        installId = try container.decode(String.self, forKey: .installId)
        attributed = try container.decode(Bool.self, forKey: .attributed)
        confidenceScore = try container.decode(Double.self, forKey: .confidenceScore)
        matchedFactors = try container.decode([String].self, forKey: .matchedFactors)

        // Organic (unattributed) installs come back as `deepLinkData: {}` rather
        // than `null`, and an object without `shortCode` carries no link to route
        // to. Treat any payload we can't decode as "no deep link" so a missing or
        // unexpected field can never fail the whole install response — that would
        // abort SDK initialization for every organic install.
        do {
            deepLinkData = try container.decodeIfPresent(DeepLinkData.self, forKey: .deepLinkData)
        } catch {
            deepLinkData = nil
            LinkFortyLogger.log("Ignoring undecodable deepLinkData in install response: \(error)")
        }
    }

    /// Creates an install response
    public init(
        installId: String,
        attributed: Bool,
        confidenceScore: Double,
        matchedFactors: [String],
        deepLinkData: DeepLinkData? = nil
    ) {
        self.installId = installId
        self.attributed = attributed
        self.confidenceScore = confidenceScore
        self.matchedFactors = matchedFactors
        self.deepLinkData = deepLinkData
    }
}

// MARK: - CustomStringConvertible

extension InstallResponse: CustomStringConvertible {
    public var description: String {
        """
        InstallResponse(
            installId: \(installId),
            attributed: \(attributed),
            confidenceScore: \(confidenceScore),
            matchedFactors: \(matchedFactors)
        )
        """
    }
}
